### ISSUE TITLE
Please provide chatGPT apiKey and try again.

### ISSUE THREAD

**Issue by mustafakoca99** [ab007shetty/chatGPT#2]
Hello,

Please provide chatGPT apiKey and try again. I am getting the error in the field.

I have entered ApiKey but I still get the same error, I couldn't understand it.

Any idea what is the problem?

Enjoy your work.

**Comment by samir240** [comment]
I also have this message. Any solution? 
thank you

**Comment by ab007shetty** [comment]
Since I'm using the free version of API, my quota got exceeded. Below is the error response. and I also updated the error handling code.

    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }

Solution - Please use your own API Key

**Comment by mustafakoca99** [comment]
Hello,

I bought and placed my own api key through openai and got the same error again. 
Am I placing it in the wrong place? 
Where should the api key be written?

enjoy your work.

**Comment by ab007shetty** [comment]
Hii Mustafa,

The ideal way to pass api key is, as url parameter.
Please find below attached screenshot.


Regards,
Anirudha

**Comment by ab007shetty** [comment]
![IMG_20230508_202535](https://user-images.githubusercontent.com/45870174/236859564-8b66ff81-aa28-44a6-97b7-2eb89b16ad9a.jpg)

**Comment by mustafakoca99** [comment]
Hello,

I tried but it didn't work

Anyway, let me try a little more.

Thank you.

**Comment by ab007shetty** [comment]
Find below attached document for reference.
[chatGPT - How to Use.docx](https://github.com/ab007shetty/chatGPT/files/11429599/chatGPT.-.How.to.Use.docx)
